# Generated by Django 4.2.7 on 2024-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_cookie',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
