# Generated by Django 4.2.7 on 2024-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.TextField(blank=True, max_length=1000)),
                ('question_id', models.CharField(max_length=50)),
                ('typed_code', models.TextField()),
                ('lang', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
