# Generated by Django 4.2.7 on 2024-02-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_solution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
